### ISSUE TITLE
logs are not being captured

### ISSUE THREAD

**Issue by allanbowe** [sasjs/angular-seed-app#201]
steps to reproduce:

1) remove the first line of code from `getdata.sas` (`%webout(FETCH)`)
2) deploy the app using `sasjs cbd`
3) try to open the table

there is an error in the console, and the log does not appear in the requests dialog

![image](https://user-images.githubusercontent.com/4420615/103876596-1fb24e00-50d4-11eb-99dd-b763fafc3253.png)

**Comment by medjedovicm** [comment]
Tested now, app breaks. Need error handling on that part. @allanbowe
